name: Django Tests Automation with GitHub Action

on:
  push:
    branches:
      - main
      - master

  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - master

jobs: