name: gh-action-dropdown-list-input


env:
  afterBuild: ${{ github.run_number }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'dev,staging,[uat],prod'
      boolean:
        type: boolean
        description: True or False
        required: True
      choice:
        type: choice
        description: Make a choice
        required: True
        options:
          - '${{ env.afterBuild }}'
          - bar
          - baz


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Print environment
       run: |
          echo "environment is ${{ github.event.inputs.environment }}"
          echo "boolean is ${{ github.event.inputs.boolean }}"
          echo "choice is ${{ github.event.inputs.choice }}"