name: gh-action-dropdown-list-input

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'dev,staging,[uat],prod'
    boolean:
        type: boolean
        description: True or False
    choice:
      type: choice
      description: Make a choice
      options:
      - foo
      - bar
      - baz

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Print environment
       run: |
          echo "environment is ${{ github.event.inputs.environment }}"
          echo "boolean is ${{ github.event.inputs.boolean }}"
          echo "choice is ${{ github.event.inputs.choice }}"